# Generated by Django 4.0.6 on 2022-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='Номер заказа')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость в долларах')),
                ('cost_rub', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость в рублях')),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
