# Generated by Django 4.0.6 on 2022-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_pk', 'order_number'], name='sheets_orde_order_p_80d1d4_idx'),
        ),
    ]
