# Generated by Django 4.0.6 on 2022-07-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_order_sheets_orde_order_p_80d1d4_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True),
        ),
    ]
