# Generated by Django 4.0.6 on 2022-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_currency_currency_sheets_curr_name_e6017b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_to_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Курс валюты к доллару'),
        ),
    ]
